### ISSUE TITLE
ECONNREFUSED 127.0.0.1:6379

### ISSUE THREAD

**Issue by adityandar** [mwafa/iptv-id#3]
Halo mas, saya coba untuk run ini di localhost tapi mendapatkan error seperti ini:
Server Start at port 3000
URL Playlist: http://localhost:3000/playlist.m3u
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
[ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)

Kira-kira apakah ada step saya yang terlewat? Saya mengikuti readme.md.
Terima kasih.

**Comment by adityandar** [comment]
Nanti minta tolong infonya ya mas kalau udah available yang tanpa cache redis, thx.

**Comment by mwafa** [comment]
Oke, nanti aku link ke pull request nya

**Comment by mwafa** [comment]
@adityandar sudah diperbaiki di https://github.com/mwafa/iptv-id/commit/00d8863621fda2d5a8f3bf5439a9d7a5530071f4

```
npx iptv-d start
```

atau bisa clone repo nya dan jalankan:
```
npm install
node index.js start
```
