### ISSUE TITLE
Vidio error

### ISSUE THREAD

**Issue by ardhipoetra** [mwafa/iptv-id#4]
Hai, 

sejak beberapa minggu lalu, kayaknya saya gak bisa akses yang dari vidio. Kalau dari vlc ada error seperti : 
```
......
main debug: resolving etslive-2-vidio-com.akamaized.net ...
gnutls debug: TLS handshake: Resource temporarily unavailable, try again.
main error: TLS session handshake timeout
main error: connection error: Resource temporarily unavailable
gnutls debug: TLS handshake: Resource temporarily unavailable, try again.
main error: TLS session handshake timeout
main error: connection error: Resource temporarily unavailable
access error: HTTP connection failure
main debug: no access modules matched
main error: no suitable access module for `https://etslive-2-vidio-com.akamaized.net:443/exp=1637280725~acl=/hls-p/ingest_1561_*/*~hmac=b37e144ae80cedfaed2d959cb6b3878c0848febbc5b7d35257d56e5c6bc5b55c/hls-p/ingest_1561_240p/index.m3u8'
........
```

Di kesempatan lain, ada error seperti ini juga : 
```
....
main debug: creating demux: access='http' demux='any' location='192.168.0.250:3000/vidio/665/index.m3u8?token=true' file='(null)'
main debug: looking for demux module matching "any": 55 candidates
es debug: cannot peek
es debug: cannot peek
es debug: cannot peek
es debug: cannot peek
es debug: cannot peek
mod debug: MOD validation failed (ext=)
ps debug: cannot peek
mpgv debug: cannot peek
mjpeg warning: no more data
mjpeg error: cannot peek
avformat warning: cannot peek
vobsub debug: could not read vobsub IDX file
ps debug: cannot peek
main debug: no demux modules matched
main debug: removing module "record"
main debug: removing module "prefetch"
main debug: removing module "access"
...
```

**Comment by mwafa** [comment]
Error pertama karena TLS sepertinya masalah di jaringan internet.

Kalau yang bawah sepertinya karena gagal generate m3u

Untuk solusi awal
Coba update VLC dan pakai npx agar dapat iptv-id versi paling baru

**Comment by mwafa** [comment]
sudah diperbarui di versi [1.3.24](https://www.npmjs.com/package/iptv-id)

di commit: https://github.com/mwafa/iptv-id/commit/d54e139ec15fe3bcd09484fdad218e3d55db9555

sekarang cache gak perlu database Redis,

semoga tidak ada masalah lagi @ardhipoetra .

**Comment by ardhipoetra** [comment]
Di vlc somehow kalau pakai link yang bukan playlist dia tetap muncul error diatas. Walaupun sudah update vlc dan ffmpeg4. Jadi sepertinya codec tidak masalah. 

Anyway, di player lain bisa, jadi issue akan ditutup. Tapi perlu dicari tahu root-cause nya sepertinya.

**Comment by ardhipoetra** [comment]
Per hari ini somehow yang source vidio tidak bisa lagi (CNN dan non-vidio sejauh ini ok). Log dari server : 

```
2022-01-18T12:31:38.409Z - GET - /vidio/205/index.m3u8?token=true
Generate Token!
TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/pi/iptv-id/node_modules/node-fetch/lib/index.js:1327:9)
    at /home/pi/iptv-id/node_modules/node-fetch/lib/index.js:1432:19
    at new Promise (<anonymous>)
    at fetch (/home/pi/iptv-id/node_modules/node-fetch/lib/index.js:1429:9)
    at fetcher (/home/pi/iptv-id/lib/fetcher.js:10:10)
    at Vidio.getHLS (/home/pi/iptv-id/lib/vidio.js:75:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/pi/iptv-id/lib/app.js:59:18
```

Sebelumnya juga ada kasus dimana tidak `TypeError` tapi video tidak sampai ke player (VLC atau semacamnya).

**Comment by mwafa** [comment]
> 

Kalau dijalankan di local dia dianggap DDOS karena ip yang sama request token terus.
solusinya biasanya pakai proxy yang ip addressnya ganti-ganti.
atau pakai cache 4 jam sekali baru generate token lagi
